name: build

on:
  push:
    branches: [ "add-username-pass-auth" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Linux 
      run: |
        go build -o ./linux/gitogram -v cmd/gitogram.go

    - name: Build Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o ./win/gitogram.exe -v cmd/gitogram.go

    - name: Upload artifacts Linux
      uses: actions/upload-artifact@v4
      with:
        name: gitogram-linux
        path: ./linux/gitogram

    - name: Upload artifacts Windows
      uses: actions/upload-artifact@v4
      with:
        name: gitogram-win
        path: ./win/gitogram.exe
